services:
  - type: web
    name: codereviewer
    runtime: java
    plan: free
    buildCommand: "mvn clean package"
    startCommand: "java -jar target/*.jar"
    autoDeploy: true
    envVars:
      - key: JAVA_VERSION
        value: 17
